CREATE TABLE IF NOT EXISTS customers (
    id SERIAL PRIMARY KEY,
    bill_to_customer_code VARCHAR(50) NOT NULL,
    bill_to_customer_name VARCHAR(100) NOT NULL,
    ar_ac_nbr VARCHAR(50),
    bill_currency VARCHAR(3),
    business_reg_nbr VARCHAR(50),
    tax_reg_nbr VARCHAR(50),
    tax_office VARCHAR(100),
    contact_person VARCHAR(100),
    tel_nbr VARCHAR(20),
    email VARCHAR(100),
    fax_nbr VARCHAR(20),
    billing_address1 VARCHAR(200),
    billing_address2 VARCHAR(200),
    billing_address3 VARCHAR(200),
    postal_code VARCHAR(20),
    city VARCHAR(100),
    state VARCHAR(100),
    country VARCHAR(100),
    payment_term_code VARCHAR(50),
    remarks TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);